In [27]:
import numpy as np

In [28]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [29]:
def mae(y_true, y_predicted):
    total_error = 0
    for yt, yp in zip(y_true, y_predicted):
        total_error += abs(yt - yp)
    print('Total error:' , total_error)
    
    mae = total_error / len(y_true)
    print("MAE:", mae)
    return mae

In [30]:
mae(y_true, y_predicted)

Total error: 2.5
MAE: 0.5


0.5

In [31]:
np.mean(np.abs(y_predicted - y_true))

0.5

In [32]:
np.log([0])

<ipython-input-32-faee82fd9f21>:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [33]:
np.log([0.000000000000000000000001])

array([-55.26204223])

In [41]:
epsilon = 1e-15

In [42]:
np.log([1e-15])

array([-34.53877639])

In [43]:
y_predicted_new = [max(i, epsilon)for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [44]:
y_predicted_new = [max(i,1 - epsilon)for i in y_predicted]
y_predicted_new

[1, 1, 0.999999999999999, 0.999999999999999, 1]

In [45]:
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)

array([ 0.00000000e+00,  0.00000000e+00, -9.99200722e-16, -9.99200722e-16,
        0.00000000e+00])

In [46]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1 - y_predicted_new))  

<ipython-input-46-e8941b194e8d>:1: RuntimeWarning: divide by zero encountered in log
  -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1 - y_predicted_new))


inf

In [47]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i, epsilon)for i in y_predicted]
    y_predicted_new = [max(i,1 - epsilon)for i in y_predicted]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1 - y_predicted_new))  

In [48]:
log_loss(y_true, y_predicted)

<ipython-input-47-b86bbbcb049a>:6: RuntimeWarning: divide by zero encountered in log
  return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1 - y_predicted_new))


inf