In [79]:
import numpy as np

In [80]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [90]:
def mae(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += abs(yp - yt)
    print("Total error is:",total_error)
    mae = total_error/len(y_predicted)
    print("Mean absolute error is:",mae)
    return mae

In [91]:
mae(y_predicted, y_true)

Total error is: 2.5
Mean absolute error is: 0.5


0.5

In [106]:
np.abs(y_predicted-y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [107]:
np.mean(np.abs(y_predicted-y_true))

0.5

In [108]:
def mae_np(y_predicted, y_true):
    return np.mean(np.abs(y_predicted-y_true))

In [109]:
mae_np(y_predicted, y_true)

0.5

In [110]:
np.log([0])

<ipython-input-110-faee82fd9f21>:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [111]:
epsilon = 1e-15

In [112]:
np.log([1e-15])

array([-34.53877639])

In [113]:
y_predicted

array([1, 1, 0, 0, 1])

In [114]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [99]:
1-epsilon

0.999999999999999

In [115]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [116]:
y_predicted_new = np.array(y_predicted_new)

In [117]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [118]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.2696280766844

In [119]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [120]:
log_loss(y_true, y_predicted)

17.2696280766844

In [121]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [123]:
def mse(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += (yp - yt)**2
    print("Total error is:",total_error)
    mse = total_error/len(y_predicted)
    print("Mean absolute error is:",mse)
    return mse

In [124]:
mse(y_predicted, y_true)

Total error is: 1.83
Mean absolute error is: 0.366


0.366

In [125]:
def mse_np(y_predicted, y_true):
    return np.mean(np.abs(y_predicted-y_true)**2)

In [126]:
mse(y_predicted, y_true)

Total error is: 1.83
Mean absolute error is: 0.366


0.366